wxapp:
  appid: wx2e384d05bfd0c623
  appsecret: ccdc310b68b14908fb028acd97f07b31


spring:
  mail:
    host: smtp.qq.com
    username: 3320243347@qq.com
    password: xiiufdyzcvdgcjbc
    default-encoding: utf-8
    protocol: smtp
    properties:
      mail:
        smtp:
          ssl: true
          auth: true
          starttls:
            enable: true
            required: true
    port: 587

  mvc:
    static-path-pattern: /image/**
  resources:
    static-locations: file:C://image/
  datasource:
    username: handa
    password: handaccount
    url: jdbc:mysql://39.107.249.209:3306/handaccount?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT


server:
  port: 443
  ssl:
    key-store: classpath:cert-1540544580228_korme.xyz.pfx
    key-store-password: r2u36ojl
    key-store-type: PKCS12



#server:
#  port: 8080
